GET http://localhost:3200/exams
Content-Type: application/json

PUT http://localhost:3200/exams
Content-Type: application/json

DELETE http://localhost:3200/exams
Content-Type: application/json


GET http://localhost:3200/getUsers
Content-Type: application/json
